OrdererOrgs:
  - Name: Orderer
    Domain: evidence-vault.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: PoliceDepartment
    Domain: police.evidence-vault.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: ForensicDepartment
    Domain: forensic.evidence-vault.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
