version: "2"

networks:
  test:

services:

  couchdbFD100:
    container_name: couchdbFD101
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=fd101
      - COUCHDB_PASSWORD=fd101
    ports:
      - 8984:5984
    volumes:
      - /var/evidence-vault/couchdb/couchdbFD101:/opt/couchdb/data
    networks:
      - test