version: "2"

networks:
  evidence:

services:
  couchdbPD100:
    container_name: couchdbPD100
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=pd100
      - COUCHDB_PASSWORD=pd100
    ports:
      - 5984:5984
    volumes:
      - /var/evidence-vault/couchdb/couchdbPD100:/opt/couchdb/data
    networks:
      - evidence


  couchdbPD101:
    container_name: couchdbPD101
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=pd101
      - COUCHDB_PASSWORD=pd101
    ports:
      - 6984:5984
    volumes:
      - /var/evidence-vault/couchdb/couchdbPD101:/opt/couchdb/data
    networks:
      - evidence


  couchdbFD100:
    container_name: couchdbFD100
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=fd100
      - COUCHDB_PASSWORD=fd100
    ports:
      - 7984:5984
    volumes:
      - /var/evidence-vault/couchdb/couchdbFD100:/opt/couchdb/data
    networks:
      - evidence


  couchdbFD101:
    container_name: couchdbFD101
    image: couchdb:3.3.3
    environment:
      - COUCHDB_USER=fd101
      - COUCHDB_PASSWORD=fd101
    ports:
      - 8984:5984
    volumes:
      - /var/evidence-vault/couchdb/couchdbFD101:/opt/couchdb/data
    networks:
      - evidence


  PD100.police.evidence-vault.com:
    container_name: PD100.police.evidence-vault.com
    image: hyperledger/fabric-peer:2.5
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=PoliceMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=PD100.police.evidence-vault.com
      - CORE_PEER_ADDRESS=PD100.police.evidence-vault.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=PD100.police.evidence-vault.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # Peer used to bootstrap gossip within organisation

      - CORE_PEER_GOSSIP_BOOTSTRAP=PD101.police.evidence-vault.com:8051

      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=PD100.police.evidence-vault.com:7051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbPD100:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=pd100
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pd100

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/police.evidence-vault.com/peers/PD100.police.evidence-vault.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/police.evidence-vault.com/peers/PD100.police.evidence-vault.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/police.evidence-vault.com/peers/PD100.police.evidence-vault.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/police.evidence-vault.com/peers/PD100.police.evidence-vault.com/msp
    depends_on:
      - couchdbPD100
    ports:
      - 7051:7051
    volumes:
      - ../artifacts/crypto-config/peerOrganizations:/etc/hyperledger/peer
      - /var/run/:/host/var/run/
      - /var/evidence-vault/peer/PD100:/var/hyperledger/production
    networks:
      - evidence


  PD101.police.evidence-vault.com:
    container_name: PD101.police.evidence-vault.com
    image: hyperledger/fabric-peer:2.5
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=PoliceMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=PD101.police.evidence-vault.com
      - CORE_PEER_ADDRESS=PD101.police.evidence-vault.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=PD101.police.evidence-vault.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # Peer used to bootstrap gossip within organisation

      - CORE_PEER_GOSSIP_BOOTSTRAP=PD100.police.evidence-vault.com:7051

      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=PD101.police.evidence-vault.com:8051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbPD101:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=pd101
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pd101

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/police.evidence-vault.com/peers/PD101.police.evidence-vault.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/police.evidence-vault.com/peers/PD101.police.evidence-vault.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/police.evidence-vault.com/peers/PD101.police.evidence-vault.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/police.evidence-vault.com/peers/PD101.police.evidence-vault.com/msp
    depends_on:
      - couchdbPD101
    ports:
      - 8051:8051
    volumes:
      - ../artifacts/crypto-config/peerOrganizations:/etc/hyperledger/peer
      - /var/run/:/host/var/run/
      - /var/evidence-vault/peer/PD101:/var/hyperledger/production
    networks:
      - evidence


  FD100.forensic.evidence-vault.com:
    container_name: FD100.forensic.evidence-vault.com
    image: hyperledger/fabric-peer:2.5
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=ForensicMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=FD100.forensic.evidence-vault.com
      - CORE_PEER_ADDRESS=FD100.forensic.evidence-vault.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=FD100.forensic.evidence-vault.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      # Peer used to bootstrap gossip within organisation

      - CORE_PEER_GOSSIP_BOOTSTRAP=FD101.forensic.evidence-vault.com:10051

      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=FD100.forensic.evidence-vault.com:9051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbFD100:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=fd100
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=fd100

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/forensic.evidence-vault.com/peers/FD100.forensic.evidence-vault.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/forensic.evidence-vault.com/peers/FD100.forensic.evidence-vault.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/forensic.evidence-vault.com/peers/FD100.forensic.evidence-vault.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/forensic.evidence-vault.com/peers/FD100.forensic.evidence-vault.com/msp
    depends_on:
      - couchdbFD100
    ports:
      - 9051:9051
    volumes:
      - ../artifacts/crypto-config/peerOrganizations:/etc/hyperledger/peer
      - /var/run/:/host/var/run/
      - /var/evidence-vault/peer/FD100:/var/hyperledger/production
    networks:
      - evidence


  FD101.forensic.evidence-vault.com:
    container_name: FD101.forensic.evidence-vault.com
    image: hyperledger/fabric-peer:2.5
    labels:
      service: hyperledger-fabric
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LOGLEVEL=info
      - CORE_PEER_LOCALMSPID=ForensicMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_test

      - CORE_PEER_ID=FD101.forensic.evidence-vault.com
      - CORE_PEER_ADDRESS=FD101.forensic.evidence-vault.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=FD101.forensic.evidence-vault.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      # Peer used to bootstrap gossip within organisation

      - CORE_PEER_GOSSIP_BOOTSTRAP=FD100.forensic.evidence-vault.com:9051

      # Exposed for discovery Service
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=FD101.forensic.evidence-vault.com:10051

      # - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9440

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbFD101:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=fd101
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=fd101

      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/peer/forensic.evidence-vault.com/peers/FD101.forensic.evidence-vault.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/peer/forensic.evidence-vault.com/peers/FD101.forensic.evidence-vault.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/peer/forensic.evidence-vault.com/peers/FD101.forensic.evidence-vault.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/forensic.evidence-vault.com/peers/FD101.forensic.evidence-vault.com/msp
    depends_on:
      - couchdbFD101
    ports:
      - 10051:10051
    volumes:
      - ../artifacts/crypto-config/peerOrganizations:/etc/hyperledger/peer
      - /var/run/:/host/var/run/
      - /var/evidence-vault/peer/FD101:/var/hyperledger/production
    networks:
      - evidence  