NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.forensic.evidence-vault.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.forensic.evidence-vault.com-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca.forensic.evidence-vault.com-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca.forensic.evidence-vault.com-cert.pem
    OrganizationalUnitIdentifier: orderer
